from .common import Handler, handle_start_auto_sync, handle_end_auto_sync
from .core import (
    handle_create_var,
    handle_create_dbuf,
    handle_create_tensor,
    handle_create_gm_tensor,
    handle_get_buf,
    handle_slice_gm_tensor,
    handle_slice_tensor,
)
from .math_ops import (
    handle_get_cube_num,
    handle_get_cube_idx,
    handle_ceil_div,
    handle_min,
    handle_mul,
    handle_div,
    handle_add,
    handle_sub,
)
from .flow import (
    handle_start_loop,
    handle_end_loop,
    handle_start_if,
    handle_start_elif,
    handle_start_else,
    handle_end_if,
)
from .cube import handle_gm_to_l1_nd2nz, handle_l1_to_l0, handle_mmad, handle_l0c_to_gm_nd2nz
from .events import (
    handle_create_devent,
    handle_create_sevent,
    handle_event_set,
    handle_event_wait,
    handle_event_setall,
    handle_event_release,
)
from .pipe_ops import (
    handle_cube_ready,
    handle_vec_ready,
    handle_wait_cube,
    handle_wait_vec,
    handle_allcube_ready,
    handle_allvec_ready,
    handle_allcube_wait,
    handle_allvec_wait,
    handle_bar,
)
from .atomic import (
    handle_atomic_add,
    handle_atomic_max,
    handle_atomic_min,
    handle_set_atomic_type,
    handle_atomic_end,
)
from .vec_binary import (
    handle_vec_add,
    handle_vec_sub,
    handle_vec_mul,
    handle_vec_div,
    handle_vec_max,
    handle_vec_min,
    handle_vec_and,
    handle_vec_or,
    handle_vec_muladddst,
)
from .vec_unary import (
    handle_vec_exp,
    handle_vec_ln,
    handle_vec_abs,
    handle_vec_rec,
    handle_vec_sqrt,
    handle_vec_rsqrt,
    handle_vec_not,
    handle_vec_relu,
)
from .vec_unary_scalar import (
    handle_vec_adds,
    handle_vec_muls,
    handle_vec_maxs,
    handle_vec_mins,
    handle_vec_lrelu,
    handle_vec_axpy,
)
from .vec_dupbrcb import handle_vec_dup, handle_vec_brcb
from .vec_gatherscatter import handle_vec_gather, handle_vec_scatter
from .vec_group import (
    handle_vec_vcadd,
    handle_vec_vcgadd,
    handle_vec_vcpadd,
    handle_vec_vcmax,
    handle_vec_vcgmax,
    handle_vec_vcmin,
    handle_vec_vcgmin,
)
from .vec_sort import handle_vec_sort32, handle_vec_mergesort4, handle_vec_mergesort_2seq
from .vec_mask import handle_set_mask, handle_reset_mask
from .vec_datamove import handle_vec_gm2ubpad, handle_vec_ub2gmpad, handle_vec_ub2ub
from .vec_cast import handle_vec_cast
from .vec_compare import handle_vec_compare, handle_vec_compares, handle_vec_set_cmpmask
from .vec_select import handle_vec_select
from .reinterpret import handle_reinterpret


def build_handlers() -> dict[str, Handler]:
    return {
        "create_var": handle_create_var,
        "create_dbuf": handle_create_dbuf,
        "create_tensor": handle_create_tensor,
        "create_gm_tensor": handle_create_gm_tensor,
        "get_cube_num": handle_get_cube_num,
        "get_cube_idx": handle_get_cube_idx,
        "ceil_div": handle_ceil_div,
        "min": handle_min,
        "mul": handle_mul,
        "div": handle_div,
        "add": handle_add,
        "sub": handle_sub,
        "get_buf": handle_get_buf,
        "slice_gm_tensor": handle_slice_gm_tensor,
        "slice_tensor": handle_slice_tensor,
        "l1_to_l0": handle_l1_to_l0,
        "start_loop": handle_start_loop,
        "end_loop": handle_end_loop,
        "start_if": handle_start_if,
        "start_elif": handle_start_elif,
        "start_else": handle_start_else,
        "end_if": handle_end_if,
        "gm_to_l1_nd2nz": handle_gm_to_l1_nd2nz,
        "mmad": handle_mmad,
        "l0c_to_gm_nd2nz": handle_l0c_to_gm_nd2nz,
        "create_devent": handle_create_devent,
        "create_sevent": handle_create_sevent,
        "event_set": handle_event_set,
        "event_wait": handle_event_wait,
        "event_setall": handle_event_setall,
        "event_release": handle_event_release,
        "BAR": handle_bar,
        "ATOMICADD": handle_atomic_add,
        "ATOMICMAX": handle_atomic_max,
        "ATOMICMIN": handle_atomic_min,
        "SETATOMICTYPE": handle_set_atomic_type,
        "ATOMICEND": handle_atomic_end,
        "cube_ready": handle_cube_ready,
        "vec_ready": handle_vec_ready,
        "wait_cube": handle_wait_cube,
        "wait_vec": handle_wait_vec,
        "allcube_ready": handle_allcube_ready,
        "allvec_ready": handle_allvec_ready,
        "allcube_wait": handle_allcube_wait,
        "allvec_wait": handle_allvec_wait,
        "ADD": handle_vec_add,
        "SUB": handle_vec_sub,
        "MUL": handle_vec_mul,
        "DIV": handle_vec_div,
        "MAX": handle_vec_max,
        "MIN": handle_vec_min,
        "AND": handle_vec_and,
        "OR": handle_vec_or,
        "MULADDDST": handle_vec_muladddst,
        "EXP": handle_vec_exp,
        "LN": handle_vec_ln,
        "ABS": handle_vec_abs,
        "REC": handle_vec_rec,
        "SQRT": handle_vec_sqrt,
        "RSQRT": handle_vec_rsqrt,
        "NOT": handle_vec_not,
        "RELU": handle_vec_relu,
        "ADDS": handle_vec_adds,
        "MULS": handle_vec_muls,
        "MAXS": handle_vec_maxs,
        "MINS": handle_vec_mins,
        "LRELU": handle_vec_lrelu,
        "AXPY": handle_vec_axpy,
        "DUP": handle_vec_dup,
        "BRCB": handle_vec_brcb,
        "GATHER": handle_vec_gather,
        "SCATTER": handle_vec_scatter,
        "VCADD": handle_vec_vcadd,
        "VCGADD": handle_vec_vcgadd,
        "VCPADD": handle_vec_vcpadd,
        "VCMAX": handle_vec_vcmax,
        "VCGMAX": handle_vec_vcgmax,
        "VCMIN": handle_vec_vcmin,
        "VCGMIN": handle_vec_vcgmin,
        "SORT32": handle_vec_sort32,
        "MERGESORT4": handle_vec_mergesort4,
        "MERGESORT2SEQ": handle_vec_mergesort_2seq,
        "SETMASK": handle_set_mask,
        "RESETMASK": handle_reset_mask,
        "GM2UBPAD": handle_vec_gm2ubpad,
        "UB2GMPAD": handle_vec_ub2gmpad,
        "UB2UB": handle_vec_ub2ub,
        "CAST": handle_vec_cast,
        "COMPARE": handle_vec_compare,
        "COMPARES": handle_vec_compares,
        "SELECT": handle_vec_select,
        "SETCMPMASK": handle_vec_set_cmpmask,
        "REINTERPRET": handle_reinterpret,
        "start_auto_sync": handle_start_auto_sync,
        "end_auto_sync": handle_end_auto_sync,
    }
