from .common import Handler, handle_start_auto_sync, handle_end_auto_sync
from .core import (
    handle_create_var,
    handle_create_reg,
    handle_create_maskreg,
    handle_create_dbuf,
    handle_create_tensor,
    handle_create_gm_tensor,
    handle_split_workspace,
    handle_get_buf,
    handle_slice_gm_tensor,
    handle_slice_tensor,
)
from .math_ops import (
    handle_get_cube_num,
    handle_get_cube_idx,
    handle_get_vec_num,
    handle_get_vec_idx,
    handle_get_sub_block_idx,
    handle_ceil_div,
    handle_min,
    handle_max,
    handle_align16,
    handle_align32,
    handle_align64,
    handle_align128,
    handle_align256,
    handle_scalar_sqrt,
    handle_mul,
    handle_div,
    handle_add,
    handle_sub,
)
from .flow import (
    handle_start_loop,
    handle_end_loop,
    handle_start_if,
    handle_start_elif,
    handle_start_else,
    handle_end_if,
)
from .cube import handle_gm_to_l1_nd2nz, handle_l1_to_l0, handle_mmad, handle_l0c_to_gm_nz2nd, handle_l0c_to_l1
from .events import (
    handle_create_devent,
    handle_create_sevent,
    handle_event_set,
    handle_event_wait,
    handle_event_setall,
    handle_event_release,
)
from .pipe_ops import (
    handle_cube_ready,
    handle_vec_ready,
    handle_wait_cube,
    handle_wait_vec,
    handle_allcube_ready,
    handle_allvec_ready,
    handle_allcube_wait,
    handle_allvec_wait,
    handle_bar,
    handle_setflag,
    handle_waitflag,
)
from .atomic import (
    handle_atomic_add,
    handle_atomic_max,
    handle_atomic_min,
    handle_set_atomic_type,
    handle_atomic_end,
)
from .vec_binary import (
    handle_vec_add,
    handle_vec_sub,
    handle_vec_mul,
    handle_vec_div,
    handle_vec_max,
    handle_vec_min,
    handle_vec_and,
    handle_vec_or,
    handle_vec_muladddst,
)
from .vec_unary import (
    handle_vec_exp,
    handle_vec_ln,
    handle_vec_abs,
    handle_vec_rec,
    handle_vec_sqrt,
    handle_vec_rsqrt,
    handle_vec_not,
    handle_vec_relu,
)
from .vec_unary_scalar import (
    handle_vec_adds,
    handle_vec_muls,
    handle_vec_maxs,
    handle_vec_mins,
    handle_vec_lrelu,
    handle_vec_axpy,
)
from .vec_dupbrcb import handle_vec_dup, handle_vec_brcb
from .vec_gatherscatter import handle_vec_gather, handle_vec_scatter
from .vec_group import (
    handle_vec_vcadd,
    handle_vec_vcgadd,
    handle_vec_vcpadd,
    handle_vec_vcmax,
    handle_vec_vcgmax,
    handle_vec_vcmin,
    handle_vec_vcgmin,
)
from .vec_sort import handle_vec_sort32, handle_vec_mergesort4, handle_vec_mergesort_2seq
from .vec_mask import handle_set_mask, handle_reset_mask
from .vec_micro import handle_call_micro
from .vec_datamove import handle_vec_gm2ubpad, handle_vec_ub2gmpad, handle_vec_ub2ub
from .vec_cast import handle_vec_cast
from .vec_compare import handle_vec_compare, handle_vec_compares, handle_vec_set_cmpmask
from .vec_select import handle_vec_select
from .reinterpret import handle_reinterpret
from .misc import handle_reset_cache


def build_handlers() -> dict[str, Handler]:
    return {
        "create_var": handle_create_var,
        "create_reg": handle_create_reg,
        "create_maskreg": handle_create_maskreg,
        "create_dbuf": handle_create_dbuf,
        "create_tensor": handle_create_tensor,
        "create_gm_tensor": handle_create_gm_tensor,
        "split_workspace": handle_split_workspace,
        "GetCubeNum": handle_get_cube_num,
        "GetCubeIdx": handle_get_cube_idx,
        "GetVecNum": handle_get_vec_num,
        "GetVecIdx": handle_get_vec_idx,
        "GetSubBlockIdx": handle_get_sub_block_idx,
        "CeilDiv": handle_ceil_div,
        "Min": handle_min,
        "Max": handle_max,
        "Align16": handle_align16,
        "Align32": handle_align32,
        "Align64": handle_align64,
        "Align128": handle_align128,
        "Align256": handle_align256,
        "scalar_sqrt": handle_scalar_sqrt,
        "var_mul": handle_mul,
        "var_div": handle_div,
        "var_add": handle_add,
        "var_sub": handle_sub,
        "get_buf": handle_get_buf,
        "slice_gm_tensor": handle_slice_gm_tensor,
        "slice_tensor": handle_slice_tensor,
        "l1_to_l0": handle_l1_to_l0,
        "start_loop": handle_start_loop,
        "end_loop": handle_end_loop,
        "start_if": handle_start_if,
        "start_elif": handle_start_elif,
        "start_else": handle_start_else,
        "end_if": handle_end_if,
        "gm_to_l1_nd2nz": handle_gm_to_l1_nd2nz,
        "mmad": handle_mmad,
        "l0c_to_gm_nz2nd": handle_l0c_to_gm_nz2nd,
        "l0c_to_l1": handle_l0c_to_l1,
        "create_devent": handle_create_devent,
        "create_sevent": handle_create_sevent,
        "event_set": handle_event_set,
        "event_wait": handle_event_wait,
        "event_setall": handle_event_setall,
        "event_release": handle_event_release,
        "barrier": handle_bar,
        "setflag": handle_setflag,
        "waitflag": handle_waitflag,
        "atomic_add": handle_atomic_add,
        "atomic_max": handle_atomic_max,
        "atomic_min": handle_atomic_min,
        "set_atomic_type": handle_set_atomic_type,
        "atomic_end": handle_atomic_end,
        "cube_ready": handle_cube_ready,
        "vec_ready": handle_vec_ready,
        "wait_cube": handle_wait_cube,
        "wait_vec": handle_wait_vec,
        "allcube_ready": handle_allcube_ready,
        "allvec_ready": handle_allvec_ready,
        "allcube_wait": handle_allcube_wait,
        "allvec_wait": handle_allvec_wait,
        "add": handle_vec_add,
        "sub": handle_vec_sub,
        "mul": handle_vec_mul,
        "div": handle_vec_div,
        "vmax": handle_vec_max,
        "vmin": handle_vec_min,
        "vand": handle_vec_and,
        "vor": handle_vec_or,
        "muladddst": handle_vec_muladddst,
        "exp": handle_vec_exp,
        "ln": handle_vec_ln,
        "abs": handle_vec_abs,
        "rec": handle_vec_rec,
        "sqrt": handle_vec_sqrt,
        "rsqrt": handle_vec_rsqrt,
        "vnot": handle_vec_not,
        "relu": handle_vec_relu,
        "adds": handle_vec_adds,
        "muls": handle_vec_muls,
        "vmaxs": handle_vec_maxs,
        "vmins": handle_vec_mins,
        "lrelu": handle_vec_lrelu,
        "axpy": handle_vec_axpy,
        "dup": handle_vec_dup,
        "brcb": handle_vec_brcb,
        "gather": handle_vec_gather,
        "scatter": handle_vec_scatter,
        "cadd": handle_vec_vcadd,
        "cgadd": handle_vec_vcgadd,
        "cpadd": handle_vec_vcpadd,
        "cmax": handle_vec_vcmax,
        "cgmax": handle_vec_vcgmax,
        "cmin": handle_vec_vcmin,
        "cgmin": handle_vec_vcgmin,
        "sort32": handle_vec_sort32,
        "mergesort4": handle_vec_mergesort4,
        "mergesort_2seq": handle_vec_mergesort_2seq,
        "set_mask": handle_set_mask,
        "reset_mask": handle_reset_mask,
        "call_micro": handle_call_micro,
        "gm_to_ub_pad": handle_vec_gm2ubpad,
        "ub_to_gm_pad": handle_vec_ub2gmpad,
        "ub_to_ub": handle_vec_ub2ub,
        "cast": handle_vec_cast,
        "compare": handle_vec_compare,
        "compare_scalar": handle_vec_compares,
        "select": handle_vec_select,
        "set_cmpmask": handle_vec_set_cmpmask,
        "reinterpret": handle_reinterpret,
        "reset_cache": handle_reset_cache,
        "start_auto_sync": handle_start_auto_sync,
        "end_auto_sync": handle_end_auto_sync,
    }
